machine:
  timezone:
    America/Los_Angeles
  ruby:
    version: 2.3.3
  hosts:
    circlehost: 127.0.0.1

dependencies:
  pre:
    - gem update --system
    - ./circle-dependencies.sh

database:
  override:
    - echo "No database configuration"

# - 'bundle exec rspec --color --require spec_helper spec --format progress':
#     environment:
#       ETL_CONFIG_DIR: "$HOME/outreach-dw/spec/config/"
test:
  pre:
    - mkdir "$HOME/config"
    # Use an empty directory for jobs
    - mkdir "$HOME/jobs"
    - "$HOME/etl/bin/generate_config_files" -i "$HOME/etl/spec/config_templates/" -o "$HOME/config/" --job-dir "$HOME/jobs" --redshift-password "falafel" --pagerduty-token "baklava"
  override:
    - rspec:
        environment:
          ETL_CONFIG_DIR: "$HOME/jobs"
